"""multiempresa + auth

Revision ID: 98df7a550919
Revises: d003ee99445b
Create Date: 2025-12-19 21:55:13.998025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '98df7a550919'
down_revision: Union[str, Sequence[str], None] = 'd003ee99445b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)

    # =========================
    # EMPRESA (solo si no existe)
    # =========================
    if "empresa" not in inspector.get_table_names():
        op.create_table(
            'empresa',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('nombre', sa.String(), nullable=False),
            sa.Column('cif', sa.String(), nullable=True),
            sa.Column('activa', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )

    # =========================
    # USER (solo si no existe)
    # =========================
    if "user" not in inspector.get_table_names():
        op.create_table(
            'user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email', sa.String(), nullable=False),
            sa.Column('password_hash', sa.String(), nullable=False),
            sa.Column('nombre', sa.String(), nullable=True),
            sa.Column('rol', sa.String(), nullable=False),
            sa.Column('activo', sa.Boolean(), nullable=False),
            sa.Column('empresa_id', sa.Integer(), nullable=False),
            sa.Column('creado', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id']),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)

    # =========================
    # EMPRESA BASE
    # =========================
    op.execute("""
    INSERT INTO empresa (id, nombre, cif, activa)
    SELECT 1, 'Default', 'N/A', 1
    WHERE NOT EXISTS (SELECT 1 FROM empresa WHERE id = 1)
    """)

    # CLIENTE
    if "empresa_id" not in [c["name"] for c in inspector.get_columns("cliente")]:
        op.add_column('cliente', sa.Column('empresa_id', sa.Integer(), nullable=True))
        op.execute("UPDATE cliente SET empresa_id = 1")

    # FACTURA
    if "empresa_id" not in [c["name"] for c in inspector.get_columns("factura")]:
        op.add_column('factura', sa.Column('empresa_id', sa.Integer(), nullable=True))
        op.execute("UPDATE factura SET empresa_id = 1")

    # EMISOR
    if "empresa_id" not in [c["name"] for c in inspector.get_columns("emisor")]:
        op.add_column('emisor', sa.Column('empresa_id', sa.Integer(), nullable=True))
        op.execute("UPDATE emisor SET empresa_id = 1")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factura', type_='foreignkey')
    op.drop_column('factura', 'empresa_id')
    op.drop_constraint(None, 'emisor', type_='foreignkey')
    op.drop_column('emisor', 'empresa_id')
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.drop_column('cliente', 'empresa_id')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('empresa')
    # ### end Alembic commands ###
