"""BASE ESTABLE

Revision ID: 9f6b954fc017
Revises: 
Create Date: 2025-12-25 08:30:27.746607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f6b954fc017'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resultado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_codigo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('origen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracionsistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verifactu_activo', sa.Boolean(), nullable=False),
    sa.Column('verifactu_modo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('verifactu_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verifactu_ultimo_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verifactu_ultimo_envio', sa.DateTime(), nullable=True),
    sa.Column('cert_aeat_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cert_aeat_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cert_aeat_valido', sa.Boolean(), nullable=False),
    sa.Column('cert_aeat_caduca_en', sa.DateTime(), nullable=True),
    sa.Column('facturas_inmutables', sa.Boolean(), nullable=False),
    sa.Column('prohibir_borrado_facturas', sa.Boolean(), nullable=False),
    sa.Column('bloquear_fechas_pasadas', sa.Boolean(), nullable=False),
    sa.Column('auditoria_activa', sa.Boolean(), nullable=False),
    sa.Column('nivel_auditoria', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('pin_habilitado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('smtp_enabled', sa.Boolean(), nullable=False),
    sa.Column('smtp_host', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('smtp_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('smtp_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('smtp_tls', sa.Boolean(), nullable=False),
    sa.Column('smtp_ssl', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cif', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresa_cif'), 'empresa', ['cif'], unique=True)
    op.create_index(op.f('ix_empresa_nombre'), 'empresa', ['nombre'], unique=False)
    op.create_table('iva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('ip_origen', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_email'), 'password_reset', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_token'), 'password_reset', ['token'], unique=True)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nif', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('poblacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_cliente_email'),
    sa.UniqueConstraint('nif', name='uq_cliente_nif')
    )
    op.create_table('emisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nif', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('poblacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('web', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('texto_pie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('texto_exento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('texto_rectificativa', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('firmar_pdf', sa.Boolean(), nullable=False),
    sa.Column('certificado_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certificado_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modo_numeracion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serie', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('serie_facturacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numeracion_plantilla', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('siguiente_numero', sa.Integer(), nullable=False),
    sa.Column('ultimo_anio_numerado', sa.Integer(), nullable=True),
    sa.Column('numeracion_bloqueada', sa.Boolean(), nullable=False),
    sa.Column('anio_numeracion_bloqueada', sa.Integer(), nullable=True),
    sa.Column('ruta_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ruta_facturas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mensaje_iva', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seguridad_pin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seguridad_timeout_min', sa.Integer(), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('seguridad_login_timeout_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('pin_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requiere_reset', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('iva_global', sa.Float(), nullable=False),
    sa.Column('iva_total', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('mensaje_iva', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rectificativa', sa.Boolean(), nullable=False),
    sa.Column('ruta_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('offline_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verifactu_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verifactu_fecha_generacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_offline_id'), 'factura', ['offline_id'], unique=False)
    op.create_table('lineafactura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepto.id'], ),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registroverifactu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_factura', sa.Date(), nullable=False),
    sa.Column('total_factura', sa.Float(), nullable=False),
    sa.Column('hash_actual', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash_anterior', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('estado_envio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_envio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registroverifactu')
    op.drop_table('lineafactura')
    op.drop_index(op.f('ix_factura_offline_id'), table_name='factura')
    op.drop_table('factura')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('emisor')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_password_reset_token'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_email'), table_name='password_reset')
    op.drop_table('password_reset')
    op.drop_table('iva')
    op.drop_index(op.f('ix_empresa_nombre'), table_name='empresa')
    op.drop_index(op.f('ix_empresa_cif'), table_name='empresa')
    op.drop_table('empresa')
    op.drop_table('configuracionsistema')
    op.drop_table('concepto')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
