"""Add SMTP config fields

Revision ID: a5bec6b5f5f7
Revises: c72dd2f37eb3
Create Date: 2025-12-21 12:56:06.602221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5bec6b5f5f7'
down_revision: Union[str, Sequence[str], None] = 'c72dd2f37eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(conn, table, column):
    rows = conn.exec_driver_sql(
        f"PRAGMA table_info({table});"
    ).fetchall()

    return any(row[1] == column for row in rows)


def upgrade() -> None:
    conn = op.get_bind()

    if not column_exists(conn, "configuracionsistema", "smtp_enabled"):
        op.add_column(
            "configuracionsistema",
            sa.Column("smtp_enabled", sa.Boolean(), nullable=False, server_default="0"),
        )

    if not column_exists(conn, "configuracionsistema", "smtp_host"):
        op.add_column(
            "configuracionsistema",
            sa.Column("smtp_host", sa.String(), nullable=True),
        )

    if not column_exists(conn, "configuracionsistema", "smtp_port"):
        op.add_column(
            "configuracionsistema",
            sa.Column("smtp_port", sa.Integer(), nullable=True),
        )

    if not column_exists(conn, "configuracionsistema", "smtp_user"):
        op.add_column(
            "configuracionsistema",
            sa.Column("smtp_user", sa.String(), nullable=True),
        )

    if not column_exists(conn, "configuracionsistema", "smtp_password"):
        op.add_column(
            "configuracionsistema",
            sa.Column("smtp_password", sa.String(), nullable=True),
        )

    if not column_exists(conn, "configuracionsistema", "smtp_tls"):
        op.add_column(
            "configuracionsistema",
            sa.Column("smtp_tls", sa.Boolean(), nullable=False, server_default="0"),
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracionsistema', 'smtp_ssl')
    op.drop_column('configuracionsistema', 'smtp_tls')
    op.drop_column('configuracionsistema', 'smtp_from')
    op.drop_column('configuracionsistema', 'smtp_password')
    op.drop_column('configuracionsistema', 'smtp_user')
    op.drop_column('configuracionsistema', 'smtp_port')
    op.drop_column('configuracionsistema', 'smtp_host')
    op.drop_column('configuracionsistema', 'smtp_enabled')
    # ### end Alembic commands ###
