"""login timeout

Revision ID: c72dd2f37eb3
Revises: c93fe8d034b1
Create Date: 2025-12-21 10:10:22.353940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72dd2f37eb3'
down_revision: Union[str, Sequence[str], None] = 'c93fe8d034b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(conn, table, column):
    result = conn.exec_driver_sql(
        f"PRAGMA table_info({table});"
    ).fetchall()

    return any(row[1] == column for row in result)


def upgrade() -> None:
    conn = op.get_bind()

    if not column_exists(conn, "emisor", "seguridad_login_timeout_min"):
        op.add_column(
            "emisor",
            sa.Column("seguridad_login_timeout_min", sa.Integer(), nullable=True)
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emisor', 'seguridad_login_timeout_min')
    op.drop_table('iva')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
