"""ampliar tabla user con pin_hash y requiere_reset

Revision ID: c93fe8d034b1
Revises: c9a971728bae
Create Date: 2025-12-20 09:19:59.359402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93fe8d034b1'
down_revision: Union[str, Sequence[str], None] = 'c9a971728bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(conn, table, column):
    result = conn.exec_driver_sql(
        f"PRAGMA table_info({table});"
    ).fetchall()

    return any(row[1] == column for row in result)


def upgrade() -> None:
    conn = op.get_bind()

    # pin_hash
    if not column_exists(conn, "user", "pin_hash"):
        op.add_column(
            "user",
            sa.Column("pin_hash", sa.String(), nullable=True)
        )

    # requiere_reset
    if not column_exists(conn, "user", "requiere_reset"):
        op.add_column(
            "user",
            sa.Column("requiere_reset", sa.Boolean(), nullable=False, server_default="0")
        )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'requiere_reset')
    op.drop_column('user', 'pin_hash')
    op.drop_constraint(None, 'factura', type_='foreignkey')
    op.alter_column('factura', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'emisor', type_='foreignkey')
    op.alter_column('emisor', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.alter_column('cliente', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
