"""creacion tablas usuario empresa passwordreset

Revision ID: c9a971728bae
Revises: c821d63187ac
Create Date: 2025-12-20 09:03:11.834432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a971728bae'
down_revision: Union[str, Sequence[str], None] = 'c821d63187ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    conn = op.get_bind()

    # comprobar si existe tabla
    existe = conn.exec_driver_sql(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='password_reset';"
    ).fetchone()

    if not existe:
        op.create_table(
            'password_reset',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('email', sa.String(), nullable=False),
            sa.Column('token', sa.String(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('used_at', sa.DateTime(), nullable=True),
            sa.Column('is_used', sa.Boolean(), nullable=False),
            sa.Column('ip_origen', sa.String(), nullable=True),
            sa.Column('tipo', sa.String(), nullable=False),
        )

        op.create_index(
            op.f('ix_password_reset_email'),
            'password_reset', ['email'], unique=False
        )

        op.create_index(
            op.f('ix_password_reset_token'),
            'password_reset', ['token'], unique=True
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factura', type_='foreignkey')
    op.alter_column('factura', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'emisor', type_='foreignkey')
    op.alter_column('emisor', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cliente', type_='foreignkey')
    op.alter_column('cliente', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_password_reset_token'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_email'), table_name='password_reset')
    op.drop_table('password_reset')
    # ### end Alembic commands ###
