"""auditoria columnas control

Revision ID: faa59d1660b5
Revises: adab9cc8a172
Create Date: 2025-12-17 17:41:07.401213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa59d1660b5'
down_revision: Union[str, Sequence[str], None] = 'adab9cc8a172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditoria')
    op.drop_table('iva')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iva',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('porcentaje', sa.FLOAT(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entidad', sa.VARCHAR(), nullable=False),
    sa.Column('entidad_id', sa.INTEGER(), nullable=True),
    sa.Column('accion', sa.VARCHAR(), nullable=False),
    sa.Column('resultado', sa.VARCHAR(), nullable=False),
    sa.Column('motivo', sa.VARCHAR(), nullable=True),
    sa.Column('usuario', sa.VARCHAR(), nullable=True),
    sa.Column('ip', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('fecha', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
