AUD_NIVEL_DESACTIVADA = "DESACTIVADA"
AUD_NIVEL_BASICA = "BASICA"
AUD_NIVEL_COMPLETA = "COMPLETA"

EV_FISCAL = "FISCAL"
EV_OPERATIVO = "OPERATIVO"
EV_ERROR = "ERROR"

RES_OK = "OK"
RES_ERROR = "ERROR"
RES_BLOQUEADO = "BLOQUEADO"
